---
title: Biografi Penulis
---

Hai, perkenalkan, saya **Agus Wibowo**, saat ini sedang melaksanakan studi pasca sarjana di [James Cook University, Australia](https://www.jcu.edu.au/).

Sedikit tentang saya. Sejak SMA saya memang suka "ngoprek", mulai dari mempelajari berbagai bahasa pemrograman seperti C++, Ruby, Python, Bash, dan R (mungkin saya adalah pengguna R pertama di Jurusan Perikanan dan Kelautan, UNILA), otak-atik program komputer hingga bongkar-pasang laptop/komputer, termasuk ngoprek Arduino dan Raspberry Pi. Dalam hal teknologi, saya berkiblat pada 2 tokoh Indonesia: [pak Budi Rahardjo](https://github.com/rahard) (sekarang dosen STEI ITB) yang mengajari saya berbagai bahasa pemrograman lewat buku-bukunya, dan [pak Onno Widodo Purbo](https://onnocenter.or.id/) yang menginspirasi saya untuk menggunakan Linux dan belajar tentang sistem keamanan komputer dan jaringan. Tetapi takdir Allah membenamkan saya untuk terjun di bidang akuakultur dan akhirnya menemukan *passion* di persimpangan antara ilmu akuakultur dan komputer: **Bioinformatika**.

Terima kasih telah mengunjungi halaman ini. Semoga konten di sini bermanfaat untuk pembelajaran dan eksplorasi Anda dalam bioinformatika!

> "***Science is the engine, and code is the fuel !!***"
>
> Agus Wibowo
